// <auto-generated />
namespace Sofia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class cambios_clientes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cambios_clientes));
        
        string IMigrationMetadata.Id
        {
            get { return "201710240311260_cambios_clientes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
